version = 0.1

[default]
[default.global.parameters]
stack_name = "document-indexing-app"

[default.build.parameters]
cached = true
parallel = true

[default.validate.parameters]
lint = true

[default.deploy.parameters]
stack_name = "document-indexing-app"
# resolve_s3 = true  # Comment out or remove this line
s3_prefix = "document-indexing-app"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""

[default.package.parameters]
# resolve_s3 = true  # Comment out or remove this line

[default.sync.parameters]
watch = true

[default.local_start_api.parameters]
warm_containers = "EAGER"

[default.local_start_lambda.parameters]
warm_containers = "EAGER"
