AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Document Indexing Application with S3 Trigger

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Tracing: Active

Resources:
  DocumentIndexingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.handler
      Runtime: python3.12
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          OPENAI_API_KEY: !Sub '{{resolve:ssm:/document-indexer/${Environment}/OPENAI_API_KEY:1}}'
          PG_HOST: !Sub '{{resolve:ssm:/document-indexer/${Environment}/PG_HOST:1}}'
          PG_PORT: !Sub '{{resolve:ssm:/document-indexer/${Environment}/PG_PORT:1}}'
          PG_DATABASE: !Sub '{{resolve:ssm:/document-indexer/${Environment}/PG_DATABASE:1}}'
          PG_USER: !Sub '{{resolve:ssm:/document-indexer/${Environment}/PG_USER:1}}'
          PG_PASSWORD: !Sub '{{resolve:ssm:/document-indexer/${Environment}/PG_PASSWORD:1}}'
      Policies:
        - S3ReadPolicy:
            BucketName: sopai-sam-data
        - SSMParameterReadPolicy:
            ParameterName: !Sub '/document-indexer/${Environment}/*'
      Events:
        S3Trigger:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events:
              - s3:ObjectCreated:*
              - s3:ObjectRemoved:*

  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: sopai-sam-data
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Function: !GetAtt DocumentIndexingFunction.Arn
          - Event: s3:ObjectRemoved:*
            Function: !GetAtt DocumentIndexingFunction.Arn

  BucketPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: 'lambda:InvokeFunction'
      FunctionName: !Ref DocumentIndexingFunction
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !GetAtt DocumentBucket.Arn

Outputs:
  DocumentIndexingFunction:
    Description: "Document Indexing Lambda Function ARN"
    Value: !GetAtt DocumentIndexingFunction.Arn
  DocumentBucket:
    Description: "S3 Bucket for documents"
    Value: !Ref DocumentBucket