AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Document Indexing Application with S3 Trigger

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

  ImageUri:
    Type: String
    Description: URI of the Docker image in ECR

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Tracing: Active

Resources:
  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'sopai-sam-data-${Environment}-${AWS::AccountId}'

  DocumentIndexingFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          PG_HOST: !Sub '{{resolve:ssm:/document-indexer/${Environment}/PG_HOST:1}}'
          PG_PORT: !Sub '{{resolve:ssm:/document-indexer/${Environment}/PG_PORT:1}}'
          PG_DATABASE: !Sub '{{resolve:ssm:/document-indexer/${Environment}/PG_DATABASE:1}}'
          PG_USER: !Sub '{{resolve:ssm:/document-indexer/${Environment}/PG_USER:1}}'
      Policies:
        - SSMParameterReadPolicy:
            ParameterName: !Sub '/document-indexer/${Environment}/*'
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
      Events:
        S3ObjectCreated:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events: s3:ObjectCreated:*
        S3ObjectRemoved:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events: s3:ObjectRemoved:*

Outputs:
  DocumentIndexingFunction:
    Description: "Document Indexing Lambda Function ARN"
    Value: !GetAtt DocumentIndexingFunction.Arn
  DocumentBucket:
    Description: "S3 Bucket for documents"
    Value: !Ref DocumentBucket