AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  ImageUri:
    Type: String
    Description: URI of the Docker image in ECR

Resources:
  DocumentIndexingFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageUri: !Ref ImageUri
      Role: arn:aws:iam::028642482223:role/DocumentIndexingFunctionRole

Outputs:
  DocumentIndexingFunction:
    Description: "Document Indexing Lambda Function ARN"
    Value: !GetAtt DocumentIndexingFunction.Arn