AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Document Indexing Application with S3 Trigger

Parameters:
  Environment:
    Type: String
    Default: dev
    AllowedValues:
      - dev
      - prod

Globals:
  Function:
    Timeout: 900
    MemorySize: 1024
    Tracing: Active

Resources:
  DocumentIndexingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./
      Handler: app.handler
      Runtime: python3.12
      Environment:
        Variables:
          ENVIRONMENT: !Ref Environment
          OPENAI_API_KEY: '{{resolve:ssm-secure:/document-indexer/${Environment}/OPENAI_API_KEY:1}}'
          PG_HOST: '{{resolve:ssm:/document-indexer/${Environment}/PG_HOST:1}}'
          PG_PORT: '{{resolve:ssm:/document-indexer/${Environment}/PG_PORT:1}}'
          PG_DATABASE: '{{resolve:ssm:/document-indexer/${Environment}/PG_DATABASE:1}}'
          PG_USER: '{{resolve:ssm:/document-indexer/${Environment}/PG_USER:1}}'
          PG_PASSWORD: '{{resolve:ssm-secure:/document-indexer/${Environment}/PG_PASSWORD:1}}'
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref DocumentBucket
        - SSMParameterReadPolicy:
            ParameterName: !Sub '/document-indexer/${Environment}/*'
      Events:
        S3ObjectCreated:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events: 
              - s3:ObjectCreated:*
        S3ObjectRemoved:
          Type: S3
          Properties:
            Bucket: !Ref DocumentBucket
            Events:
              - s3:ObjectRemoved:*

  DocumentBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'sopai-sam-data-${Environment}-${AWS::AccountId}'

Outputs:
  DocumentIndexingFunction:
    Description: "Document Indexing Lambda Function ARN"
    Value: !GetAtt DocumentIndexingFunction.Arn
  DocumentBucket:
    Description: "S3 Bucket for documents"
    Value: !Ref DocumentBucket