name: Deploy SAM Application

on:
  push:
    branches:
      - "dev"
  workflow_dispatch:

env:
  PIPELINE_USER_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  PIPELINE_USER_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SAM_TEMPLATE: template.yaml
  TESTING_STACK_NAME: document-indexing-dev
  TESTING_PIPELINE_EXECUTION_ROLE: arn:aws:iam::028642482223:role/GithubActionsSAMDeploymentRole
  TESTING_CLOUDFORMATION_EXECUTION_ROLE: arn:aws:iam::028642482223:role/CloudFormationSAMExecutionRole
  TESTING_ARTIFACTS_BUCKET: document-indexer-sam-artifacts
  TESTING_REGION: us-east-1
  ECR_REPOSITORY: document-indexer-rep
  IMAGE_TAG: latest

jobs:
  build-and-deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ env.PIPELINE_USER_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ env.PIPELINE_USER_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.TESTING_REGION }}
          role-to-assume: ${{ env.TESTING_PIPELINE_EXECUTION_ROLE }}
          role-session-name: dev-deployment
          role-duration-seconds: 3600
          role-skip-session-tagging: true

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      - name: Deploy to dev stack
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_IMAGE: "${{ steps.login-ecr.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}"
        run: |
          sam deploy --stack-name ${TESTING_STACK_NAME} \
            --capabilities CAPABILITY_IAM \
            --region ${TESTING_REGION} \
            --s3-bucket ${TESTING_ARTIFACTS_BUCKET} \
            --no-fail-on-empty-changeset \
            --parameter-overrides Environment=dev ImageUri=${ECR_IMAGE} \
            --image-repository $ECR_REGISTRY/$ECR_REPOSITORY \
            --no-confirm-changeset \
            --disable-rollback
            --role-arn arn:aws:iam::028642482223:role/DocumentIndexingFunctionRole